// <auto-generated />
using System;
using FauG.Gateway.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FauG.Gateway.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260224003241_Phase3_TokenUsage")]
    partial class Phase3_TokenUsage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FauG.Gateway.Core.Entities.ModelCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("InputCostPer1k")
                        .HasColumnType("numeric");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("OutputCostPer1k")
                        .HasColumnType("numeric");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ModelCost");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InputCostPer1k = 0.002m,
                            ModelName = "gpt-4o",
                            OutputCostPer1k = 0.00125m,
                            Provider = "OpenAI"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InputCostPer1k = 0.0005m,
                            ModelName = "gpt-3.5-turbo",
                            OutputCostPer1k = 0.0015m,
                            Provider = "OpenAI"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            InputCostPer1k = 0.00059m,
                            ModelName = "llama3-70b-8192",
                            OutputCostPer1k = 0.00079m,
                            Provider = "Groq"
                        });
                });

            modelBuilder.Entity("FauG.Gateway.Core.Entities.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalCurrentSpend")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalMontlyBudget")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Orgatisations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Test Org",
                            TotalCurrentSpend = 0m,
                            TotalMontlyBudget = 1000m
                        });
                });

            modelBuilder.Entity("FauG.Gateway.Core.Entities.ProviderAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("ProviderAccounts");
                });

            modelBuilder.Entity("FauG.Gateway.Core.Entities.RequestLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("numeric");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProviderAccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("integer");

                    b.Property<Guid>("VirtualKeyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProviderAccountId");

                    b.HasIndex("VirtualKeyId");

                    b.ToTable("RequestLogs");
                });

            modelBuilder.Entity("FauG.Gateway.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Access")
                        .HasColumnType("boolean");

                    b.Property<decimal>("AllocatedBudget")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentSpend")
                        .HasColumnType("numeric");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Access = false,
                            AllocatedBudget = 1000m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentSpend = 0m,
                            OrganisationId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        });
                });

            modelBuilder.Entity("FauG.Gateway.Core.Entities.VirtualKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("VirtualKeys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRevoked = false,
                            KeyHash = "4Eewl8OQ7obBcMby4ZfuZyaYglxZ0VdkDYo6SFs/6g8=",
                            LastUsedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        });
                });

            modelBuilder.Entity("FauG.Gateway.Core.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("AllowedModels")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MaxTokenSpend")
                        .HasColumnType("numeric");

                    b.Property<int>("RequestsPerMinute")
                        .HasColumnType("integer");

                    b.Property<Guid>("VirtualKeyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VirtualKeyId")
                        .IsUnique();

                    b.ToTable("Policies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            AllowedModels = new[] { "gpt-4o", "llama3-70b-8192" },
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxTokenSpend = 1000m,
                            RequestsPerMinute = 60,
                            VirtualKeyId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        });
                });

            modelBuilder.Entity("FauG.Gateway.Core.Entities.ProviderAccount", b =>
                {
                    b.HasOne("FauG.Gateway.Core.Entities.Organisation", "Organisation")
                        .WithMany("ProviderAccounts")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("FauG.Gateway.Core.Entities.RequestLog", b =>
                {
                    b.HasOne("FauG.Gateway.Core.Entities.ProviderAccount", "ProviderAccount")
                        .WithMany()
                        .HasForeignKey("ProviderAccountId");

                    b.HasOne("FauG.Gateway.Core.Entities.VirtualKey", "VirtualKey")
                        .WithMany("RequestLogs")
                        .HasForeignKey("VirtualKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProviderAccount");

                    b.Navigation("VirtualKey");
                });

            modelBuilder.Entity("FauG.Gateway.Core.Entities.User", b =>
                {
                    b.HasOne("FauG.Gateway.Core.Entities.Organisation", "Organisation")
                        .WithMany("Users")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("FauG.Gateway.Core.Entities.VirtualKey", b =>
                {
                    b.HasOne("FauG.Gateway.Core.Entities.User", "User")
                        .WithMany("VirtualKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FauG.Gateway.Core.Policy", b =>
                {
                    b.HasOne("FauG.Gateway.Core.Entities.VirtualKey", "VirtualKey")
                        .WithOne("Policy")
                        .HasForeignKey("FauG.Gateway.Core.Policy", "VirtualKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VirtualKey");
                });

            modelBuilder.Entity("FauG.Gateway.Core.Entities.Organisation", b =>
                {
                    b.Navigation("ProviderAccounts");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("FauG.Gateway.Core.Entities.User", b =>
                {
                    b.Navigation("VirtualKeys");
                });

            modelBuilder.Entity("FauG.Gateway.Core.Entities.VirtualKey", b =>
                {
                    b.Navigation("Policy")
                        .IsRequired();

                    b.Navigation("RequestLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
