// <auto-generated />
using System;
using FauG.Gateway.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FauG.Gateway.Core.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260217153507_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FauG.Gateway.Core.Entities.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalCurrentSpend")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalMontlyBudget")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Orgatisations");
                });

            modelBuilder.Entity("FauG.Gateway.Core.Entities.ProviderAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("ProviderAccounts");
                });

            modelBuilder.Entity("FauG.Gateway.Core.Entities.RequestLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("numeric");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProviderAccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<Guid>("VirtualKeyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProviderAccountId");

                    b.HasIndex("VirtualKeyId");

                    b.ToTable("RequestLogs");
                });

            modelBuilder.Entity("FauG.Gateway.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Access")
                        .HasColumnType("boolean");

                    b.Property<decimal>("AllocatedBudget")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentSpend")
                        .HasColumnType("numeric");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FauG.Gateway.Core.Entities.VirtualKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("VirtualKeys");
                });

            modelBuilder.Entity("FauG.Gateway.Core.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string[]>("AllowedModels")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MaxTokenSpend")
                        .HasColumnType("numeric");

                    b.Property<int>("RequestsPerMinute")
                        .HasColumnType("integer");

                    b.Property<Guid>("VirtualKeyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VirtualKeyId")
                        .IsUnique();

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("FauG.Gateway.Core.Entities.ProviderAccount", b =>
                {
                    b.HasOne("FauG.Gateway.Core.Entities.Organisation", "Organisation")
                        .WithMany("ProviderAccounts")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("FauG.Gateway.Core.Entities.RequestLog", b =>
                {
                    b.HasOne("FauG.Gateway.Core.Entities.ProviderAccount", "ProviderAccount")
                        .WithMany()
                        .HasForeignKey("ProviderAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FauG.Gateway.Core.Entities.VirtualKey", "VirtualKey")
                        .WithMany("RequestLogs")
                        .HasForeignKey("VirtualKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProviderAccount");

                    b.Navigation("VirtualKey");
                });

            modelBuilder.Entity("FauG.Gateway.Core.Entities.User", b =>
                {
                    b.HasOne("FauG.Gateway.Core.Entities.Organisation", "Organisation")
                        .WithMany("Users")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("FauG.Gateway.Core.Entities.VirtualKey", b =>
                {
                    b.HasOne("FauG.Gateway.Core.Entities.User", "User")
                        .WithMany("VirtualKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FauG.Gateway.Core.Policy", b =>
                {
                    b.HasOne("FauG.Gateway.Core.Entities.VirtualKey", "VirtualKey")
                        .WithOne("Policy")
                        .HasForeignKey("FauG.Gateway.Core.Policy", "VirtualKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VirtualKey");
                });

            modelBuilder.Entity("FauG.Gateway.Core.Entities.Organisation", b =>
                {
                    b.Navigation("ProviderAccounts");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("FauG.Gateway.Core.Entities.User", b =>
                {
                    b.Navigation("VirtualKeys");
                });

            modelBuilder.Entity("FauG.Gateway.Core.Entities.VirtualKey", b =>
                {
                    b.Navigation("Policy")
                        .IsRequired();

                    b.Navigation("RequestLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
